# Practice Case - Statistic
## Data Fellowship Program <br>Batch 6

### Scenario
The data-set contains aggregate individual statistics for 67 NBA seasons. from basic box-score attributes such as points, assists, rebounds etc., to more advanced money-ball like features such as Value Over Replacement.

### Pre-processing
In this task not all data will be used, only data in 2017. So it is necessary to do filtering at the beginning. Besides that there are some players who make team transfers in the NBA transfer market so that there is duplication of player data. Therefore you can use the df.drop_duplicates() syntax to solve this to produce the same output as the trainer. Delete columns that have as many missing values as the entire row of data. Then you can do additional preprocessing if needed or you can immediately process the data.

In [1]:
import pandas as pd #import library
url='https://raw.githubusercontent.com/Syukrondzeko/Fellowship/main/Seasons_Stats.csv'
df=pd.read_csv(url,index_col=0) #import data

In [2]:
df2017=df[df['Year']==2017] # Filter data NBA Season Year on 2017
df2017.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
24096,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0
24097,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,0.750,20.0,95.0,115.0,18.0,14.0,15.0,21.0,67.0,222.0
24098,2017.0,Quincy Acy,PF,26.0,DAL,6.0,0.0,48.0,-1.4,0.355,...,0.667,2.0,6.0,8.0,0.0,0.0,0.0,2.0,9.0,13.0
24099,2017.0,Quincy Acy,PF,26.0,BRK,32.0,1.0,510.0,13.1,0.587,...,0.754,18.0,89.0,107.0,18.0,14.0,15.0,19.0,58.0,209.0
24100,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,0.611,282.0,333.0,615.0,86.0,88.0,78.0,146.0,195.0,905.0

In [3]:
df2017.drop_duplicates('Player',keep='first',inplace=True)# drop duplicates players name and keep the first row
missing_value=df2017.isnull().sum() # check missing value
missing_value[missing_value>0]

<ipython-input-3-b85ec743c9dc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2017.drop_duplicates('Player',keep='first',inplace=True)# drop duplicates players name and keep the first row

TS%         1
3PAr        1
FTr         1
TOV%        1
blanl     486
blank2    486
FG%         1
3P%        36
2P%         2
eFG%        1
FT%        15
dtype: int64

In [4]:
# Because variable blanl and blank2 have missing value as the entire row of data then both of them will be drop
df2017.drop(['blanl','blank2'],axis=1,inplace=True)
df2017.fillna(0.0,inplace=True) # impute the rest of variable with 0 value

C:\Users\User\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\User\anaconda3\lib\site-packages\pandas\core\frame.py:4317: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [5]:
missing_value=df2017.isnull().sum() # check missing value after missing value treatment
missing_value[missing_value>0]

Series([], dtype: int64)

### Process clean data
##### Some goals of this project:

1.	Who is the youngest and oldest player in the NBA in 2017 for each team (Tm) ?

In [28]:
young=df2017.loc[df2017.groupby('Tm')['Age'].idxmin()]
young[['Player','Tm','Age']].sort_values('Age').reset_index(drop=True)#youngest player each team

                     Player   Tm   Age
0                Thon Maker  MIL  19.0
1             Dragan Bender  PHO  19.0
2      Georgios Papagiannis  SAC  19.0
3              Jamal Murray  DEN  19.0
4            Brandon Ingram  LAL  19.0
5             Diamond Stone  LAC  19.0
6           Justise Winslow  MIA  20.0
7             Cheick Diallo  NOP  20.0
8                Tyus Jones  MIN  20.0
9              Wade Baldwin  MEM  20.0
10             Myles Turner  IND  20.0
11           Chinanu Onuaku  HOU  20.0
12             Kevon Looney  GSW  20.0
13           Henry Ellenson  DET  20.0
14          Dejounte Murray  SAS  20.0
15             Jaylen Brown  BOS  20.0
16         Domantas Sabonis  OKC  20.0
17        Stephen Zimmerman  ORL  20.0
18              Noah Vonleh  POR  21.0
19            Bruno Caboclo  TOR  21.0
20         Chris McCullough  TOT  21.0
21  Timothe Luwawu-Cabarrot  PHI  21.0
22              Kelly Oubre  WAS  21.0
23               Dante Exum  UTA  21.0
24               Ben Bentil  DAL  21.0
25               Kay Felder  CLE  21.0
26           Christian Wood  CHO  21.0
27             Bobby Portis  CHI  21.0
28         Isaiah Whitehead  BRK  21.0
29       Kristaps Porzingis  NYK  21.0
30          DeAndre' Bembry  ATL  22.0

In [31]:
old=df2017.loc[df2017.groupby('Tm')['Age'].idxmax()]
old[['Player','Tm','Age']].sort_values('Age',ascending=False).reset_index(drop=True) #oldest player each team

             Player   Tm   Age
0      Vince Carter  MEM  40.0
1       Jason Terry  MIL  39.0
2     Manu Ginobili  SAS  39.0
3       Paul Pierce  LAC  39.0
4    Chris Andersen  CLE  38.0
5     Dirk Nowitzki  DAL  38.0
6       Metta World  LAL  37.0
7     Udonis Haslem  MIA  36.0
8       Matt Barnes  TOT  36.0
9     Nick Collison  OKC  36.0
10       David West  GSW  36.0
11      Mike Miller  DEN  36.0
12       Luis Scola  BRK  36.0
13      Joe Johnson  UTA  35.0
14      Dwyane Wade  CHI  35.0
15       Beno Udrih  DET  34.0
16       John Lucas  MIN  34.0
17  Leandro Barbosa  PHO  34.0
18     Nene Hilario  HOU  34.0
19     Jarrett Jack  NOP  33.0
20   Tiago Splitter  PHI  32.0
21        Gary Neal  ATL  32.0
22      C.J. Watson  ORL  32.0
23  Carmelo Anthony  NYK  32.0
24     Aaron Brooks  IND  32.0
25    Marcin Gortat  WAS  32.0
26    Arron Afflalo  SAC  31.0
27     Gerald Green  BOS  31.0
28    Brian Roberts  CHO  31.0
29  DeMarre Carroll  TOR  30.0
30      Evan Turner  POR  28.0

2.	Which player has the most minutes played (MP) in each position (Pos)?

In [36]:
df_mp=df2017.loc[df2017.groupby('Pos')['MP'].idxmax()]
df_mp[['Player','Tm','Pos','MP']].sort_values('MP',ascending=False).reset_index(drop=True) # Highest MP

               Player   Tm   Pos      MP
0      Andrew Wiggins  MIN    SF  3048.0
1  Karl-Anthony Towns  MIN     C  3030.0
2        James Harden  HOU    PG  2947.0
3     Harrison Barnes  DAL    PF  2803.0
4       C.J. McCollum  POR    SG  2796.0
5   Joffrey Lauvergne  TOT  PF-C   980.0

3.	Which team has the highest average total rebound percentage (TRB%), assist percentage (AST%), steal percentage (STL%), and block percentage (BLK%)?

In [10]:
team=df2017[['Tm','TRB%','AST%','STL%','BLK%']].groupby('Tm',as_index=False).mean()

In [11]:
team[team['TRB%']==team['TRB%'].max()][['Tm','TRB%']]

     Tm   TRB%
30  WAS  13.45

In [12]:
team[team['AST%']==team['AST%'].max()][['Tm','AST%']]

    Tm   AST%
7  DEN  15.86

In [13]:
team[team['STL%']==team['STL%'].max()][['Tm','STL%']]

     Tm      STL%
17  MIN  2.371429

In [14]:
team[team['BLK%']==team['BLK%'].max()][['Tm','BLK%']]

    Tm  BLK%
9  GSW  2.74

4.	Who is the best player in your opinion based on his record stats? note: you can refer to variables point (PTS), assists, rebounds, or anything else. A combination of several variables would be nice.

In [15]:
best_player=df2017[['Player','Pos','Tm','PTS','AST','TRB','PER','TS%','eFG%']] #get some variable to measure best player

In [16]:
# To make the scale of chosen variables same, so min max scaler will be use as the additional preprocessing
from sklearn.preprocessing import MinMaxScaler #import library
scaler = MinMaxScaler()
best_player[['PTS','AST','TRB','PER','TS%','eFG%']] = scaler.fit_transform(best_player[['PTS','AST','TRB','PER','TS%','eFG%']])

<ipython-input-16-d112adb5591b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  best_player[['PTS','AST','TRB','PER','TS%','eFG%']] = scaler.fit_transform(best_player[['PTS','AST','TRB','PER','TS%','eFG%']])
C:\Users\User\anaconda3\lib\site-packages\pandas\core\indexing.py:1736: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value[:, i].tolist())

In [17]:
best_player['avg_measure']=best_player.mean(axis=1) #make new variable as the aggregate metric to measure overall feature
best_player[best_player['avg_measure']==best_player['avg_measure'].max()] # best player based on highest average measure

<ipython-input-17-2dea32935a2c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  best_player['avg_measure']=best_player.mean(axis=1) #make new variable as the aggregate metric to measure overall feature

,Player,Pos,Tm,PTS,AST,TRB,PER,TS%,eFG%,avg_measure
24654,Russell Westbrook,PG,OKC,1.0,0.927152,0.774194,0.98167,0.693367,0.476,0.80873

5.	Which team has the best average stat record of their players? Note: you can refer to points, assists, rebounds, or anything else. A combination of several variables would be nice

In [19]:
best_team=best_player.groupby('Tm').mean() # aggregate average each variable based on Team
best_team.head()

          PTS       AST       TRB       PER       TS%      eFG%  avg_measure
Tm
ATL  0.199427  0.128992  0.196834  0.568771  0.594493  0.426267     0.352464
BOS  0.230831  0.152244  0.205615  0.659470  0.701293  0.539667     0.414854
BRK  0.204987  0.125670  0.202189  0.616090  0.666726  0.489643     0.384217
CHI  0.215463  0.144846  0.220223  0.606455  0.599596  0.446692     0.372213
CHO  0.224254  0.140807  0.205069  0.606634  0.622117  0.447857     0.374456

In [20]:
best_team[best_team['avg_measure']==best_team['avg_measure'].max()] ## best team based on highest average measure

          PTS       AST       TRB       PER       TS%      eFG%  avg_measure
Tm
GSW  0.244384  0.179544  0.212007  0.672505  0.712307  0.540267     0.426836